[build]
    command: npm run build
    commandOrigin: config
    environment:
    - NEXT_PRIVATE_TARGET
    publish: /opt/build/repo/out_publish
    publishOrigin: config
    functionsDirectory: /opt/build/repo/out_functions
[plugins]:
- inputs: {}
    origin: ui
    package: '@netlify/plugin-nextjs'